#!/bin/bash

SRC_DIR=`dirname "$0"`
TEST_DIR="/sibis-software/python-packages/sibispy/sibispy/tests"

CFG_FILE=/home/ncanda/.sibis-general-config.yml 
LEGACY_TESTS=(test_utils.py test_config_file_parser.py test_redcap_to_casesdir.py test_redcap_locking_data.py test_redcap_compute_summary_scores.py)
MODERN_TESTS=(test_post_issues_to_github.py test_sibislogger.py test_xnat_util.py test_session.py test_sibis_svn_util.py test_sibis_email.py test_check_dti_gradients.py)

logFile=`mktemp`
for TEST in ${MODERN_TESTS[@]}; do  
  echo " " 
  echo " " 
  CMD="pytest -v --config-file=${CFG_FILE} ${TEST_DIR}/${TEST}"
  echo "========================="
  echo "==== $CMD" 
  echo "========================="
  $CMD | tee -a $logFile
done 

echo " " 
echo " " 

echo "========================="
echo "========================="
echo "========================="
echo "Failed pytests:"
grep FAILED $logFile  
rm $logFile 
echo "========================="
echo "========================="
echo "========================="

for TEST in ${LEGACY_TESTS[@]}; do  
  echo " " 
  echo " " 
  CMD="${TEST_DIR}/$TEST ${CFG_FILE}"
  echo "========================="
  echo "====  LEGACY ${TEST}"
  echo "==== $CMD" 
  echo "========================="
  $CMD 
done 