#!/bin/bash
CFG_FILE=~/.sibis-general-config.yml 
LEGACY_TESTS=(test_utils.py test_config_file_parser.py test_redcap_to_casesdir.py test_redcap_locking_data.py test_redcap_compute_summary_scores.py)
MODERN_TESTS=(test_post_issues_to_github.py test_sibislogger.py test_xnat_util.py test_session.py test_sibis_svn_util.py test_sibis_email.py test_check_dti_gradients.py)

for TEST in ${MODERN_TESTS[@]}; do  
  echo " " 
  echo " " 
  echo "========================="
  echo "====  MODERN ${TEST}"
  echo "====  pytest -v --config-file=${CFG_FILE} ../tests/${TEST}"
  echo "========================="
  pytest -v --config-file=${CFG_FILE} ../tests/${TEST}
done 

for TEST in ${LEGACY_TESTS[@]}; do  
  echo " " 
  echo " " 
  echo "========================="
  echo "====  LEGACY ${TEST}"
  echo "====  ../tests/${TEST} ${CFG_FILE}"
  echo "========================="
  ../tests/${TEST} ${CFG_FILE} 
done 
